"""
q3_coset_clustering.py

Coset clustering analysis for Collatz v2 discrepancies in ZMod(13)*.

The multiplicative group (Z/13Z)* has order 12.
The subgroup generated by 3 is {1, 3, 9} (order 3), creating 4 cosets:
  Coset A: {1, 3, 9}    -- Trinity subgroup
  Coset B: {2, 6, 5}    -- 2 * {1,3,9} mod 13
  Coset C: {4, 12, 10}  -- 4 * {1,3,9} mod 13
  Coset D: {8, 11, 7}   -- 8 * {1,3,9} mod 13  (8 = 2^3, highest power of 2 below 13)
  Class 0: {0}           -- multiples of 13

For each k in 3..7, we find all "unsafe" residues r mod M (M = 13 * 2^k, r odd)
where v2(3r+1) >= k (the modular computation claims the carry propagates at least k bits),
then compare against the actual minimum v2 over integers n ≡ r (mod M).

Discrepancy = modular_v2 - min_actual_v2 >= 0.
"""

import json


# ---------------------------------------------------------------------------
# Step 1: Coset classification
# ---------------------------------------------------------------------------

def get_coset(r_mod13):
    """Return coset label for r mod 13 in (Z/13Z)*."""
    if r_mod13 == 0:
        return '0'
    coset_A = {1, 3, 9}
    coset_B = {2, 6, 5}
    coset_C = {4, 12, 10}
    coset_D = {8, 11, 7}
    if r_mod13 in coset_A:
        return 'A'
    if r_mod13 in coset_B:
        return 'B'
    if r_mod13 in coset_C:
        return 'C'
    if r_mod13 in coset_D:
        return 'D'
    return '?'


# ---------------------------------------------------------------------------
# Step 2: v2 computation and unsafe residue discovery
# ---------------------------------------------------------------------------

def v2(n):
    """2-adic valuation of n. Returns -1 if n == 0."""
    if n == 0:
        return -1
    return (n & -n).bit_length() - 1


def get_unsafe_residues(k, n_limit=50000):
    """
    Return list of dicts for each unsafe residue r mod M (M = 13 * 2^k).

    An unsafe residue is an odd r in [1, M) where v2(3r+1) >= k.
    This means the modular computation overestimates the carry length for
    some concrete integers n ≡ r (mod M).

    Fields: r, mod13, coset, modular_v2, min_actual_v2, discrepancy
    """
    M = 13 * (2 ** k)
    results = []
    for r in range(1, M, 2):  # odd residues only
        mod_v2 = v2(3 * r + 1)
        if mod_v2 >= k:
            # Collect actual v2 values for n ≡ r (mod M), 1 <= n <= n_limit
            actual_v2_values = []
            n = r
            while n <= n_limit:
                actual_v2_values.append(v2(3 * n + 1))
                n += M
            if actual_v2_values:
                min_actual = min(actual_v2_values)
                disc = mod_v2 - min_actual
                r_mod13 = r % 13
                coset = get_coset(r_mod13)
                results.append({
                    'r': r,
                    'mod13': r_mod13,
                    'coset': coset,
                    'modular_v2': mod_v2,
                    'min_actual_v2': min_actual,
                    'discrepancy': disc,
                })
    return results


# ---------------------------------------------------------------------------
# Step 3 & 4: Aggregate by coset
# ---------------------------------------------------------------------------

def aggregate_by_coset(results):
    """
    Returns dict: coset_label -> {
        'residues': [...],
        'discrepancies': [...],
        'max_disc': int,
        'sum_disc': int,
    }
    """
    cosets = {'A': [], 'B': [], 'C': [], 'D': [], '0': []}
    for entry in results:
        c = entry['coset']
        cosets[c].append(entry)

    agg = {}
    for label, entries in cosets.items():
        residues = [e['r'] for e in entries]
        discs = [e['discrepancy'] for e in entries]
        agg[label] = {
            'residues': residues,
            'discrepancies': discs,
            'max_disc': max(discs) if discs else 0,
            'sum_disc': sum(discs),
        }
    return agg


# ---------------------------------------------------------------------------
# Step 5: Trace the worst offender
# ---------------------------------------------------------------------------

def trace_worst_offender():
    """
    Trace r=85 at k=3 in detail.
    v2(3*85 + 1) = v2(256) = 8
    256 = 2^8, so modular_v2 = 8.
    But k=3 so only 3 carry bits are "safe" — rest is discrepancy.
    """
    r = 85
    k = 3
    M = 13 * (2 ** k)  # = 104
    val = 3 * r + 1     # = 256

    print("\n=== Step 5: Tracing worst offender r=85 (k=3) ===")
    print(f"  r = {r}, k = {k}, M = {M}")
    print(f"  3r + 1 = {val} = 2^{v2(val)}")
    print(f"  modular_v2 = {v2(val)}, but k = {k}")
    print(f"  discrepancy = {v2(val)} - {k} = {v2(val) - k}")
    print(f"  (The modular arithmetic treats r≡85 as if 3r+1 is divisible by 2^8,")
    print(f"   but the modulus M=104 only guarantees 3 bits of carry precision.)")
    print()

    # Show first several n ≡ 85 (mod 104) and their v2 values
    print(f"  Actual v2(3n+1) for n ≡ {r} (mod {M}):")
    n = r
    count = 0
    while n <= 104 * 20 and count < 12:
        actual = v2(3 * n + 1)
        flag = " <-- LOW (discrepancy here)" if actual < v2(val) else ""
        print(f"    n={n:6d}: 3n+1={3*n+1:8d}, v2={actual}{flag}")
        n += M
        count += 1

    # Check successor: after one Collatz step from r=85 in mod M
    # 3*85 + 1 = 256 = 2^8, divide by 2^8 gives 1, then... but for the residue class:
    # The "successor" residue class is (3r+1) / 2^k mod M (if divisible)
    # Here 3*85+1 = 256 = 2^8, so divide by 2^k=8 gives 256/8=32, but we want mod M:
    successor_val = (3 * r + 1) >> k  # divide by 2^k
    successor_r = successor_val % M
    if successor_r % 2 == 0:
        # Not an odd residue; find the odd part
        pass
    print(f"\n  After one Collatz step (divide by 2^k={k}):")
    print(f"  (3*{r}+1) / 2^{k} = {3*r+1} / {2**k} = {successor_val}")
    print(f"  successor residue mod {M} = {successor_r}")
    print(f"  successor mod 13 = {successor_r % 13}, coset = {get_coset(successor_r % 13)}")

    # Also check what happens if we divide by full v2 (8 levels)
    full_div = val >> v2(val)
    full_div_mod = full_div % M
    print(f"\n  If we divide by full 2^8={2**8}:")
    print(f"  {val} / {2**8} = {full_div}")
    print(f"  full successor mod {M} = {full_div_mod}")
    print(f"  full successor mod 13 = {full_div_mod % 13}, coset = {get_coset(full_div_mod % 13)}")


# ---------------------------------------------------------------------------
# Step 6 & 7: Print tables and save JSON
# ---------------------------------------------------------------------------

def print_coset_table(k, agg):
    M = 13 * (2 ** k)
    coset_sets = {
        'A': '{1,3,9}',
        'B': '{2,6,5}',
        'C': '{4,12,10}',
        'D': '{8,11,7}',
        '0': '{0}',
    }
    print(f"\n=== k={k} (modulus {M}) ===")
    for label in ['D', 'A', 'B', 'C', '0']:
        data = agg[label]
        name = "Class 0" if label == '0' else f"Coset {label}"
        print(f"  {name} = {coset_sets[label]:12s}: "
              f"residues {data['residues']}, "
              f"discrepancies {data['discrepancies']}, "
              f"max={data['max_disc']}, sum={data['sum_disc']}")

    # Find worst coset
    worst_label = max(['A', 'B', 'C', 'D', '0'], key=lambda c: (agg[c]['max_disc'], agg[c]['sum_disc']))
    worst = agg[worst_label]
    print(f"\n  Worst coset: {worst_label} (max={worst['max_disc']}, sum={worst['sum_disc']})")


def main():
    all_results = {}
    summary_rows = []

    for k in range(3, 8):  # k = 3, 4, 5, 6, 7
        results = get_unsafe_residues(k)
        agg = aggregate_by_coset(results)
        print_coset_table(k, agg)

        # Find worst coset for summary
        worst_label = max(['A', 'B', 'C', 'D', '0'],
                          key=lambda c: (agg[c]['max_disc'], agg[c]['sum_disc']))
        worst_max = agg[worst_label]['max_disc']
        worst_sum = agg[worst_label]['sum_disc']
        summary_rows.append((k, worst_label, worst_max, worst_sum, agg))

        all_results[str(k)] = {
            'k': k,
            'modulus': 13 * (2 ** k),
            'unsafe_residues': results,
            'coset_aggregation': {
                label: {
                    'residues': agg[label]['residues'],
                    'discrepancies': agg[label]['discrepancies'],
                    'max_disc': agg[label]['max_disc'],
                    'sum_disc': agg[label]['sum_disc'],
                }
                for label in ['A', 'B', 'C', 'D', '0']
            },
            'worst_coset': worst_label,
            'worst_max': worst_max,
            'worst_sum': worst_sum,
        }

    # Step 5: trace worst offender
    trace_worst_offender()

    # Summary
    print("\n=== SUMMARY: Does Coset D dominate across all k? ===")
    d_wins = 0
    for k, label, mx, sm, agg in summary_rows:
        marker = " <-- D WINS" if label == 'D' else ""
        print(f"  k={k}: worst={label} (max_disc={mx}, sum={sm}){marker}")
        if label == 'D':
            d_wins += 1

    print()
    if d_wins == len(summary_rows):
        print(f"  YES: Coset D dominates in ALL {len(summary_rows)} values of k tested.")
    elif d_wins > len(summary_rows) // 2:
        print(f"  MOSTLY: Coset D dominates in {d_wins}/{len(summary_rows)} values of k.")
    else:
        print(f"  NO: Coset D dominates in only {d_wins}/{len(summary_rows)} values of k.")

    # Additional: show per-k coset max discrepancies in a compact table
    print("\n=== Per-k coset max discrepancy table ===")
    header = f"  {'k':>3}  {'mod':>6}  {'coset_A':>9}  {'coset_B':>9}  {'coset_C':>9}  {'coset_D':>9}  {'class_0':>9}"
    print(header)
    print("  " + "-" * (len(header) - 2))
    for k, label, mx, sm, agg in summary_rows:
        M = 13 * (2 ** k)
        row = (f"  {k:>3}  {M:>6}  "
               f"{agg['A']['max_disc']:>9}  "
               f"{agg['B']['max_disc']:>9}  "
               f"{agg['C']['max_disc']:>9}  "
               f"{agg['D']['max_disc']:>9}  "
               f"{agg['0']['max_disc']:>9}")
        print(row)

    # Step 7: Save to JSON
    output_path = '/Users/dcharb/Documents/collatz/UFRF0-Lean4-Explore-v2/exploration/q3_results.json'
    with open(output_path, 'w') as f:
        json.dump(all_results, f, indent=2)
    print(f"\nResults saved to {output_path}")


if __name__ == '__main__':
    main()
