-- AUTO-GENERATED IMPORTS
-- This section is automatically generated by scripts/sync_modules.py
import UFRF.Addressing
import UFRF.Adele
import UFRF.AllenBridge
import UFRF.AllenEmbedding
import UFRF.AlphaRunning
import UFRF.AngularEmbedding
import UFRF.AxiomAudit
import UFRF.BreathingCycle
import UFRF.Calculus
import UFRF.CircleIntegralBreathing
import UFRF.ComplexBreathing
import UFRF.Constants
import UFRF.DivisionAlgebras
import UFRF.FibonacciKissing
import UFRF.FibonacciPrimeChain
import UFRF.FineStructure
import UFRF.Foundation
import UFRF.Fourier
import UFRF.GoldenAngle
import UFRF.InverseLimit
import UFRF.KeplerTriangle
import UFRF.KernelProof
import UFRF.KissingEigen
import UFRF.KissingHierarchy
import UFRF.Manifold
import UFRF.Noether
import UFRF.NumberBases
import UFRF.NumerizationSeeds
import UFRF.PRISMAlgebra
import UFRF.Padic
import UFRF.PhaseSpaceCartography
import UFRF.Phenomena
import UFRF.PositionalPhase
import UFRF.PrimeChoreography
import UFRF.PrimeSemantics
import UFRF.Projections
import UFRF.QUART
import UFRF.Recursion
import UFRF.ResidueDefinition
import UFRF.Simplex
import UFRF.StarPolygon
import UFRF.Structure13
import UFRF.ThreeLOG
import UFRF.Trinity
import UFRF.Waveform

/-!
# Universal Field Resonance Framework — Lean 4 Formalization

## The Single Axiom
Everything derives from the Trinity: `{-½, 0, +½}` with sum = 0.
-/
