#!/usr/bin/env python3
"""Generate a lightweight declaration index for a Lean source file.

This tool is intentionally source-driven rather than environment-driven:
it gives quick local name/namespace/line lookup for active proof files without
requiring a Lean build or guessing from memory.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


NAMESPACE_RE = re.compile(r"^namespace\s+([A-Za-z0-9_.'`]+)\s*$")
END_RE = re.compile(r"^end(?:\s+([A-Za-z0-9_.'`]+))?\s*$")
DECL_RE = re.compile(
    r"^(?P<mods>(?:(?:private|protected|noncomputable|unsafe|partial|opaque)\s+)*)"
    r"(?P<kind>theorem|lemma|def|abbrev|structure|class|inductive|axiom|instance)\s+"
    r"(?P<name>[^\s(:{]+)"
)


@dataclass
class DeclEntry:
    line: int
    namespace: str
    full_name: str
    short_name: str
    kind: str
    modifiers: str
    doc_summary: str


def clean_doc(doc: str) -> str:
    text = doc
    text = re.sub(r"^/\-\-+\s*", "", text.strip())
    text = re.sub(r"\s*-\*/\s*$", "", text)
    lines = [line.strip() for line in text.splitlines()]
    nonempty = [line for line in lines if line]
    if not nonempty:
        return ""
    joined = " ".join(nonempty)
    return re.sub(r"\s+", " ", joined).strip()


def first_sentence(text: str) -> str:
    if not text:
        return ""
    match = re.search(r"(.+?[.!?])(?:\s|$)", text)
    if match:
        return match.group(1).strip()
    return text


def parse_declarations(lines: list[str]) -> list[DeclEntry]:
    namespace_stack: list[str] = []
    entries: list[DeclEntry] = []
    pending_doc: str | None = None
    in_doc = False
    doc_lines: list[str] = []

    for lineno, raw_line in enumerate(lines, start=1):
        line = raw_line.rstrip("\n")
        stripped = line.strip()

        if in_doc:
            doc_lines.append(line)
            if "-/" in stripped:
                pending_doc = clean_doc("\n".join(doc_lines))
                in_doc = False
                doc_lines = []
            continue

        if stripped.startswith("/--"):
            in_doc = True
            doc_lines = [line]
            if "-/" in stripped and stripped != "/--":
                pending_doc = clean_doc("\n".join(doc_lines))
                in_doc = False
                doc_lines = []
            continue

        ns_match = NAMESPACE_RE.match(stripped)
        if ns_match:
            namespace_stack.append(ns_match.group(1))
            pending_doc = None
            continue

        end_match = END_RE.match(stripped)
        if end_match:
            name = end_match.group(1)
            if name:
                while namespace_stack:
                    top = namespace_stack.pop()
                    if top == name or top.endswith(f".{name}"):
                        break
            pending_doc = None
            continue

        if line.startswith("@[") or stripped.startswith("attribute "):
            continue

        if line and not line.startswith(" "):
            decl_match = DECL_RE.match(stripped)
            if decl_match:
                namespace = ".".join(namespace_stack)
                short_name = decl_match.group("name")
                full_name = ".".join(part for part in [namespace, short_name] if part)
                modifiers = " ".join(decl_match.group("mods").split())
                doc_summary = first_sentence(pending_doc or "")
                entries.append(
                    DeclEntry(
                        line=lineno,
                        namespace=namespace or "(root)",
                        full_name=full_name,
                        short_name=short_name,
                        kind=decl_match.group("kind"),
                        modifiers=modifiers,
                        doc_summary=doc_summary,
                    )
                )
                pending_doc = None
            elif stripped and not stripped.startswith("--") and not stripped.startswith("/-"):
                pending_doc = None

    return entries


def render_markdown(
    title: str,
    source: Path,
    entries: Iterable[DeclEntry],
    generated_at: str,
) -> str:
    grouped: dict[str, list[DeclEntry]] = defaultdict(list)
    ordered_entries = list(entries)
    for entry in ordered_entries:
        grouped[entry.namespace].append(entry)

    namespaces = sorted(grouped)
    lines = [
        f"# {title}",
        "",
        "This file is generated by `scripts/generate_decl_index.py`.",
        "",
        "- Lean source remains authoritative for exact statements and rewrite shapes.",
        "- Use this index for fast local name/namespace/line lookup before proof edits.",
        "",
        "## Metadata",
        "",
        f"- Source: `{source.as_posix()}`",
        f"- Generated: `{generated_at}`",
        f"- Declarations: `{len(ordered_entries)}`",
        f"- Namespaces: `{len(namespaces)}`",
        "",
        "## Workflow",
        "",
        "1. Use Rover to recover the current theorem cluster and best next family.",
        "2. Use this index plus `rg` in source to verify exact local declaration names.",
        "3. If the index and source ever disagree, trust source and regenerate the index.",
        "",
    ]

    for namespace in namespaces:
        lines.extend(
            [
                f"## `{namespace}`",
                "",
                "| Line | Kind | Name | Modifiers | Doc |",
                "| ---: | --- | --- | --- | --- |",
            ]
        )
        for entry in grouped[namespace]:
            doc = entry.doc_summary.replace("|", "\\|")
            modifiers = entry.modifiers or ""
            lines.append(
                f"| {entry.line} | `{entry.kind}` | `{entry.short_name}` | "
                f"`{modifiers}` | {doc} |"
            )
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Lean source file to index")
    parser.add_argument("--json", required=True, help="Output JSON path")
    parser.add_argument("--markdown", required=True, help="Output Markdown path")
    parser.add_argument("--title", required=True, help="Markdown document title")
    args = parser.parse_args()

    source = Path(args.input)
    json_path = Path(args.json)
    markdown_path = Path(args.markdown)
    source_text = source.read_text(encoding="utf-8")
    entries = parse_declarations(source_text.splitlines(keepends=True))
    generated_at = datetime.now(timezone.utc).isoformat()

    json_path.parent.mkdir(parents=True, exist_ok=True)
    markdown_path.parent.mkdir(parents=True, exist_ok=True)

    payload = {
        "title": args.title,
        "source": source.as_posix(),
        "generated_at": generated_at,
        "declaration_count": len(entries),
        "entries": [asdict(entry) for entry in entries],
    }
    json_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    markdown_path.write_text(
        render_markdown(args.title, source, entries, generated_at) + "\n",
        encoding="utf-8",
    )

    print(
        f"Generated {len(entries)} declarations from {source} -> "
        f"{markdown_path} and {json_path}"
    )


if __name__ == "__main__":
    main()
